### ISSUE TITLE
Compatibility with today's `modlib`

### ISSUE THREAD

**Issue by zeuner** [appgurueu/voxelizer#3] opened 2023-06-23 12:32 UTC
It turns out that the `voxelizer` can't be used with up-to-date version of its `modlib` dependency (https://github.com/appgurueu/modlib). Trying to start it results in an error in this (https://github.com/appgurueu/voxelizer/blob/master/conf.lua#L55) line as `modlib.conf` is `nil`.

It can be worked around by downgrading `modlib`, but it would be preferable to be able to use the `voxelizer` in an up-to-date setup.

**Comment by appgurueu** [comment] 2023-06-23 12:52
You're right. A long while ago I removed the `conf` module from `modlib`. I ought to upgrade `voxelizer` all my mods which relied on it to use the new module superseeding it, but I didn't get to it for `voxelizer` (and wanted to rewrite `voxelizer` anyways).

**Comment by appgurueu** [comment] 2023-06-26 15:06
Fixed in https://github.com/appgurueu/voxelizer/commit/eae1ade683503a357856bc232bef078ee1d12196

**Closed as completed by appgurueu** 2023-06-26 15:06 UTC
Labels: bug

**Comment by zeuner** [comment] 2023-06-27 14:14
Thanks... do I need to change anything in the world config for the new version to work? I'm getting this now (latest git commits for `voxelizer`, `modlib` and `cmdlib`):

```
ERROR[Main]: ModError: Failed to load and run script from /mnt/voxtest/minetest-engine/bin/../mods/voxelizer/init.lua:
ERROR[Main]: (load):55: attempt to index global 'modlib' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: ?
ERROR[Main]: 	(load):55: in main chunk
ERROR[Main]: 	.../minetest-engine/bin/../mods/modlib/minetest/mod.lua:113: in function 'read'
ERROR[Main]: 	.../minetest-engine/bin/../mods/modlib/minetest/mod.lua:146: in function 'add'
ERROR[Main]: 	.../minetest-engine/bin/../mods/modlib/minetest/mod.lua:152: in function 'configuration'
ERROR[Main]: 	...xtest/minetest-engine/bin/../mods/voxelizer/init.lua:18: in main chunk
ERROR[Main]: Check debug.txt for details.
ACTION[Main]: Server: Shutting down
```

**Comment by appgurueu** [comment] 2023-06-27 18:38
I tried with a fresh world and I couldn't reproduce.

* Line 152 is: **`add(get_resource(modname, "conf"))`** - this is about mod, not world conf
* Line 146 is: `overrides = modlib.table.deep_add_all(overrides, format.read(content))`
* Line 113 is: `local additions =  setfenv(assert(loadstring(text)), setmetatable(overrides, {__index = {_C = overrides}}))()`

What's happening here is that there is a file `conf.lua` which is the old `conf.lua` (which has `config = modlib.conf.import("voxelizer", conf_spec)` at line 55) in `voxelizer`'s mod folder which `modlib` is trying to load as a configuration file. This of course fails because `modlib` is not present in the environment.

However I just checked and https://github.com/appgurueu/voxelizer/commit/eae1ade683503a357856bc232bef078ee1d12196 deleted `conf.lua`.

I really wonder why `conf.lua` is still present for you; it definitely shouldn't be there. It isn't there for me. I just checked the CDB release and it isn't there either.

Either way this is very confusing: You somehow seem to still have `conf.lua`, but also have `schema.lua`. It's as if https://github.com/appgurueu/voxelizer/commit/eae1ade683503a357856bc232bef078ee1d12196 had only been partially applied...

**Comment by zeuner** [comment] 2023-06-27 20:04
My bad. I had copied the new version over the old mod directory, which of course made all deletions ineffective.

Thanks for the insightful analysis, though. From the error message alone it wasn't obvious that a `conf.lua` could be the problem.

**Comment by appgurueu** [comment] 2023-06-28 10:42
Yeah. The issue here is that `modlib` doesn't use `loadfile` or pass the filename to `load`, thus you just get a cryptic `(load):<error>`. Will address.
